# Generated by Django 4.0 on 2021-12-17 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('is_superuser', models.BooleanField(blank=True, default=False)),
                ('profile_pic', models.FileField(null=True, upload_to='profile_pics/')),
                ('referral', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('card_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.FileField(upload_to='photo/')),
                ('livephoto', models.FileField(upload_to='livephoto')),
                ('documentname', models.CharField(max_length=255)),
                ('documentid', models.CharField(max_length=255)),
                ('documentfront', models.FileField(upload_to='documentfront')),
                ('documentback', models.FileField(upload_to='documentback')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
