# Generated by Django 4.0 on 2021-12-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='card_number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
