# Generated by Django 4.0 on 2021-12-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_options_alter_profile_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=30)),
                ('confirm_account_no', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=30)),
                ('iban_no', models.CharField(max_length=30)),
                ('swift_code', models.CharField(max_length=30)),
                ('passbook', models.FileField(upload_to='passbook/')),
            ],
        ),
    ]
